esphome:
  name: "m5-atom-matrix"

esp32:
  board: esp32dev
  framework:
    type: arduino

logger:

api:

ota:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

captive_portal:

# Stolen directly from
# https://community.home-assistant.io/t/example-m5stack-atom-matrix-with-led-matrix-effect-no-home-assistant/298419/5
# I didn't try to do anything yet with the outputs which are pretty unfiltered but,
# you can shake it and see the numbers change in HA and that's half the battle.
i2c:
  sda: 25
  scl: 21
  scan: true

sensor:
  - platform: mpu6886
    address: 0x68
    update_interval: 300ms
    accel_x:
      name: "MPU6886 Accel X"
    accel_y:
      name: "MPU6886 Accel Y"
    accel_z:
      name: "MPU6886 Accel z"
    gyro_x:
      name: "MPU6886 Gyro X"
    gyro_y:
      name: "MPU6886 Gyro Y"
    gyro_z:
      name: "MPU6886 Gyro z"
    temperature:
      name: "MPU6886 Temperature"
