esphome:
  name: "m5-atom-matrix"

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: my-ssid
    password: my-password

captive_portal:

light:
  - platform: fastled_clockless
    chipset: WS2812B
    pin: 27
    num_leds: 25
    rgb_order: GRB
    name: "led_matrix"
    id: led_matrix_light
    default_transition_length: .25s
    color_correct: [50%, 50%, 50%]
    restore_mode: ALWAYS_ON

# I can't say this worked out SUPER well (colors weren't what I hoped) but it did work.
# I hand created a gif out of 5x5 pixel images to verify that the orientation and frames
# were correct, then uploaded the file to HA using the Samba add-on.
# It has to go in the config/esphome directory.
display:
  - platform: addressable_light
    id: led_matrix_display
    addressable_light_id: led_matrix_light
    width: 5
    height: 5
    update_interval: 500ms
    lambda: |-
      // Draw the image my_image at position [x=0,y=0]
      // it.image(0, 0, id(test_sunset));

      id(test_sunset).next_frame();
      // Draw the animation my_animation at position [x=0,y=0]
      it.image(0, 0, id(test_sunset), COLOR_ON, COLOR_OFF);

animation:
  - file: "images/pixels.gif"
    id: test_sunset
    resize: 5x5
    type: RGB24
